default_stages: [push,]
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black --check
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]

