[tool.poetry]
name = "base"
version = "0.1.0"
description = "Base project setup"
authors = ["Andrea Riciputi <andrea.riciputi@gmail.com>"]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
